name: Cache Refresh 

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  ping-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ping Plumfield Moms Pages
        run: |
          LOG_FILE="ping-log.csv"

          # Add header if file doesn't exist
          if [ ! -f "$LOG_FILE" ]; then
            echo "timestamp,url,status,time_ms" > "$LOG_FILE"
          fi

          urls=(
            "https://plumfieldmoms.com"
            "https://plumfieldmoms.com/book-reviews-picture-book"
            "https://plumfieldmoms.com/book-reviews-plumfield-kids"
            "https://plumfieldmoms.com/book-reviews-plumfield-interns"
            "https://plumfieldmoms.com/book-club-guides"
            "https://plumfieldmoms.com/book-lists"
            "https://plumfieldmoms.com/favorite-authors"
            "https://plumfieldmoms.com/wonder-boxes"
            "https://plumfieldmoms.com/green-writer-program"
            "https://plumfieldmoms.com/tags-database/tag-small-publishers"
            "https://plumfieldmoms.com/pages/spelling"
          )

          for url in "${urls[@]}"; do
            echo "Pinging $url ..."
            start_time=$(date +%s%3N)
            status_code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
            end_time=$(date +%s%3N)
            elapsed=$((end_time - start_time))
            timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            echo "$timestamp,$url,$status_code,$elapsed" >> "$LOG_FILE"
            echo "Status: $status_code, Time: ${elapsed}ms"
          done

      - name: Commit log file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$GH_PAT" ]; then
            echo "GH_PAT secret is not set. Exiting."
            exit 1
          fi
          git config user.name "GitHub Actions"
          git config user.email "masarikfamilymichael@gmail.com"
          git add ping-log.csv
          git commit -m "Update cache log" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/$GITHUB_REPOSITORY HEAD:main
